global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # Order Service
  - job_name: 'order-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['orderservice:8080']
        labels:
          service: 'order-service'

  # Payment Service
  - job_name: 'payment-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['paymentservice:8080']
        labels:
          service: 'payment-service'

  # Inventory Service
  - job_name: 'inventory-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['inventoryservice:8080']
        labels:
          service: 'inventory-service'

  # Saga Coordinator
  - job_name: 'saga-coordinator'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['sagacoordinator:8080']
        labels:
          service: 'saga-coordinator'

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']